Only send diff notifications for non auto-deploys

diff --git a/bin/k-ctl b/bin/k-ctl
--- a/bin/k-ctl
+++ b/bin/k-ctl
@@ -153,7 +153,11 @@ case "$ACTION" in
       helm_diff | tee /tmp/helm-diff
       # Send a diff notification, allowed to
       # fail so we don't block the pipeline
-      /k8s-workloads/notify-mr -d /tmp/helm-diff -e "$environment" || echo "WARNING: notify-mr diff notification failed"
+      # Skip the notifications for auto-deploy triggered pipelines since they are not
+      # done in the context of an MR.
+      if [[ $AUTO_DEPLOY == "false" ]]; then
+        /k8s-workloads/notify-mr -d /tmp/helm-diff -e "$environment" || echo "WARNING: notify-mr diff notification failed"
+      fi
       debug "-------" "${_CYN}"
     else
       tail --pid=$$ --retry --follow "${HELM_TILLER_LOGS_DIR}" &
